#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("wave_android_uitest.Resource", IsApplication=true)]

namespace wave_android_uitest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int in_from_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int in_from_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int out_to_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int out_to_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int sm_text_label = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int sm_text_month_label = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int sm_text_size = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int sm_text_value = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int text_filter = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int text_name = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_norm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int activity_sel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ActivityTab_Selected2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ActivityTab_Unselected2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrow_filled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blue_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CalendarTab_Selected2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CalendarTab_Unselected2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ChallengeButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int challenges = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int challenges_norm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int challenges_sel = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ChallengesTab_Selected2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ChallengesTab_Unselected2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int CheckMarkB = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dateBgCircle = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dateBgWide = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dividerF = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int down_arrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int excl_triangle = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int FriendsTab_Selected2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int FriendsTab_Unselected2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int global_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int graph_placeholder = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int green_check = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int HeaderBg = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int LevelAmount = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int LevelColoredCircle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int my_life = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int mylife_norm = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int mylife_sel = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int people = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int people_norm = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int people_sel = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int person_outline = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int red_button = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int red_check = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int RemoveButton = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int StatsIcon_Selected = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int test_tile_bg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int transparent = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int u23 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int u61 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int u62 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int white_button = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int XMarkB = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09007b
			public const int action_activity = 2131296379;
			
			// aapt resource value: 0x7f09007d
			public const int action_challenges = 2131296381;
			
			// aapt resource value: 0x7f09007c
			public const int action_my_life = 2131296380;
			
			// aapt resource value: 0x7f09007e
			public const int action_people = 2131296382;
			
			// aapt resource value: 0x7f090002
			public const int activity_limage = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int activity_pager = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int activity_rimage = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int activity_root = 2131296256;
			
			// aapt resource value: 0x7f090066
			public const int activity_tab_bar = 2131296358;
			
			// aapt resource value: 0x7f090005
			public const int activity_text1 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int activity_text2 = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int activity_time = 2131296260;
			
			// aapt resource value: 0x7f090065
			public const int body = 2131296357;
			
			// aapt resource value: 0x7f09000e
			public const int day_detail_back_month = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int day_detail_bg_image = 2131296266;
			
			// aapt resource value: 0x7f090013
			public const int day_detail_cal_count = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int day_detail_cal_label = 2131296276;
			
			// aapt resource value: 0x7f09000f
			public const int day_detail_current_date = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int day_detail_header = 2131296268;
			
			// aapt resource value: 0x7f090015
			public const int day_detail_mi_count = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int day_detail_mi_label = 2131296278;
			
			// aapt resource value: 0x7f090010
			public const int day_detail_photo_text = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int day_detail_right_arrow = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int day_detail_root = 2131296265;
			
			// aapt resource value: 0x7f090011
			public const int day_detail_step_count = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int day_detail_step_label = 2131296274;
			
			// aapt resource value: 0x7f09000b
			public const int day_detail_txt_layout = 2131296267;
			
			// aapt resource value: 0x7f090031
			public const int editText1 = 2131296305;
			
			// aapt resource value: 0x7f090033
			public const int forgot_password = 2131296307;
			
			// aapt resource value: 0x7f090017
			public const int friend_stats_layout = 2131296279;
			
			// aapt resource value: 0x7f090019
			public const int fs_challenge_button = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int fs_pager = 2131296280;
			
			// aapt resource value: 0x7f090027
			public const int fsi_graph_placeholder = 2131296295;
			
			// aapt resource value: 0x7f090024
			public const int fsi_hours_count = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int fsi_hours_label = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int fsi_miles_count = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int fsi_miles_label = 2131296289;
			
			// aapt resource value: 0x7f09001d
			public const int fsi_newer_button = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int fsi_older_button = 2131296286;
			
			// aapt resource value: 0x7f09001b
			public const int fsi_parent_layout = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int fsi_scroll = 2131296282;
			
			// aapt resource value: 0x7f090025
			public const int fsi_stat_divider = 2131296293;
			
			// aapt resource value: 0x7f090020
			public const int fsi_steps_count = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int fsi_steps_label = 2131296287;
			
			// aapt resource value: 0x7f09002c
			public const int fsi_user_hour_count = 2131296300;
			
			// aapt resource value: 0x7f09002b
			public const int fsi_user_hour_label = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int fsi_user_mile_count = 2131296298;
			
			// aapt resource value: 0x7f090029
			public const int fsi_user_mile_label = 2131296297;
			
			// aapt resource value: 0x7f090028
			public const int fsi_user_step_count = 2131296296;
			
			// aapt resource value: 0x7f090026
			public const int fsi_user_step_label = 2131296294;
			
			// aapt resource value: 0x7f09001c
			public const int fsi_view_title = 2131296284;
			
			// aapt resource value: 0x7f090063
			public const int imageView1 = 2131296355;
			
			// aapt resource value: 0x7f090079
			public const int login = 2131296377;
			
			// aapt resource value: 0x7f090032
			public const int login_btn = 2131296306;
			
			// aapt resource value: 0x7f09002e
			public const int login_facebook = 2131296302;
			
			// aapt resource value: 0x7f09002d
			public const int login_layout = 2131296301;
			
			// aapt resource value: 0x7f090061
			public const int logo = 2131296353;
			
			// aapt resource value: 0x7f090044
			public const int my_life_calendar_toggle = 2131296324;
			
			// aapt resource value: 0x7f090051
			public const int my_life_gt_arrow = 2131296337;
			
			// aapt resource value: 0x7f090036
			public const int my_life_header = 2131296310;
			
			// aapt resource value: 0x7f090045
			public const int my_life_header_bg = 2131296325;
			
			// aapt resource value: 0x7f090035
			public const int my_life_header_frame = 2131296309;
			
			// aapt resource value: 0x7f09004d
			public const int my_life_lt_arrow = 2131296333;
			
			// aapt resource value: 0x7f09004c
			public const int my_life_month_bar = 2131296332;
			
			// aapt resource value: 0x7f09004f
			public const int my_life_month_text = 2131296335;
			
			// aapt resource value: 0x7f09004e
			public const int my_life_newer_text = 2131296334;
			
			// aapt resource value: 0x7f090050
			public const int my_life_older_text = 2131296336;
			
			// aapt resource value: 0x7f09004a
			public const int my_life_opponent_challenge_text = 2131296330;
			
			// aapt resource value: 0x7f090046
			public const int my_life_opponent_layout = 2131296326;
			
			// aapt resource value: 0x7f090049
			public const int my_life_opponent_left = 2131296329;
			
			// aapt resource value: 0x7f090048
			public const int my_life_opponent_remove_txt = 2131296328;
			
			// aapt resource value: 0x7f090047
			public const int my_life_opponent_right = 2131296327;
			
			// aapt resource value: 0x7f090054
			public const int my_life_page_grid = 2131296340;
			
			// aapt resource value: 0x7f090053
			public const int my_life_page_root = 2131296339;
			
			// aapt resource value: 0x7f090052
			public const int my_life_pager = 2131296338;
			
			// aapt resource value: 0x7f09004b
			public const int my_life_pager_parent = 2131296331;
			
			// aapt resource value: 0x7f090034
			public const int my_life_root_layout = 2131296308;
			
			// aapt resource value: 0x7f090056
			public const int my_life_tile_bg_image = 2131296342;
			
			// aapt resource value: 0x7f09005b
			public const int my_life_tile_count_txt = 2131296347;
			
			// aapt resource value: 0x7f090058
			public const int my_life_tile_fg_frame = 2131296344;
			
			// aapt resource value: 0x7f090059
			public const int my_life_tile_fg_image = 2131296345;
			
			// aapt resource value: 0x7f09005a
			public const int my_life_tile_fg_text = 2131296346;
			
			// aapt resource value: 0x7f090057
			public const int my_life_tile_info = 2131296343;
			
			// aapt resource value: 0x7f090055
			public const int my_life_tile_root = 2131296341;
			
			// aapt resource value: 0x7f090040
			public const int my_life_user_check_text = 2131296320;
			
			// aapt resource value: 0x7f09003e
			public const int my_life_user_divider1 = 2131296318;
			
			// aapt resource value: 0x7f090041
			public const int my_life_user_divider2 = 2131296321;
			
			// aapt resource value: 0x7f090037
			public const int my_life_user_image = 2131296311;
			
			// aapt resource value: 0x7f090039
			public const int my_life_user_info = 2131296313;
			
			// aapt resource value: 0x7f090038
			public const int my_life_user_name = 2131296312;
			
			// aapt resource value: 0x7f090042
			public const int my_life_user_x = 2131296322;
			
			// aapt resource value: 0x7f090043
			public const int my_life_user_x_text = 2131296323;
			
			// aapt resource value: 0x7f09003b
			public const int my_life_user_xp_bar = 2131296315;
			
			// aapt resource value: 0x7f09003f
			public const int my_life_user_xp_check = 2131296319;
			
			// aapt resource value: 0x7f09003c
			public const int my_life_user_xp_image = 2131296316;
			
			// aapt resource value: 0x7f09003a
			public const int my_life_user_xp_layout = 2131296314;
			
			// aapt resource value: 0x7f09003d
			public const int my_life_user_xp_text = 2131296317;
			
			// aapt resource value: 0x7f090007
			public const int option_cb = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int option_text = 2131296264;
			
			// aapt resource value: 0x7f090073
			public const int pager = 2131296371;
			
			// aapt resource value: 0x7f090074
			public const int parent_view = 2131296372;
			
			// aapt resource value: 0x7f090076
			public const int rb11 = 2131296374;
			
			// aapt resource value: 0x7f090077
			public const int rb12 = 2131296375;
			
			// aapt resource value: 0x7f090078
			public const int rb13 = 2131296376;
			
			// aapt resource value: 0x7f090075
			public const int rg1 = 2131296373;
			
			// aapt resource value: 0x7f09005f
			public const int root = 2131296351;
			
			// aapt resource value: 0x7f09005d
			public const int sign_btn = 2131296349;
			
			// aapt resource value: 0x7f09005c
			public const int sign_facebook = 2131296348;
			
			// aapt resource value: 0x7f09007a
			public const int signup = 2131296378;
			
			// aapt resource value: 0x7f090062
			public const int spinner = 2131296354;
			
			// aapt resource value: 0x7f090060
			public const int splash = 2131296352;
			
			// aapt resource value: 0x7f090068
			public const int tab_bar_activity_image = 2131296360;
			
			// aapt resource value: 0x7f090067
			public const int tab_bar_activity_layout = 2131296359;
			
			// aapt resource value: 0x7f090069
			public const int tab_bar_activity_text = 2131296361;
			
			// aapt resource value: 0x7f09006e
			public const int tab_bar_challenge_image = 2131296366;
			
			// aapt resource value: 0x7f09006f
			public const int tab_bar_challenge_text = 2131296367;
			
			// aapt resource value: 0x7f09006d
			public const int tab_bar_challenges_layout = 2131296365;
			
			// aapt resource value: 0x7f09006b
			public const int tab_bar_my_life_image = 2131296363;
			
			// aapt resource value: 0x7f09006a
			public const int tab_bar_my_life_layout = 2131296362;
			
			// aapt resource value: 0x7f09006c
			public const int tab_bar_my_life_text = 2131296364;
			
			// aapt resource value: 0x7f090071
			public const int tab_bar_people_image = 2131296369;
			
			// aapt resource value: 0x7f090070
			public const int tab_bar_people_layout = 2131296368;
			
			// aapt resource value: 0x7f090072
			public const int tab_bar_people_text = 2131296370;
			
			// aapt resource value: 0x7f09002f
			public const int textView1 = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int textView2 = 2131296304;
			
			// aapt resource value: 0x7f09005e
			public const int textView3 = 2131296350;
			
			// aapt resource value: 0x7f090064
			public const int title = 2131296356;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int small_text = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_option_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int day_detail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int friend_stats = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int friend_stats_insert = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int my_life = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int my_life_page = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int my_life_tile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int signup = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int splash = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int tab1 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int tab_bar = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int test2_layout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int test_layout = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_actions = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070006
			public const int actionbar_activity = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int activity_action = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int challenges_action = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int my_life_action = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int people_action = 2131165189;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
