#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("wave_android_uitest.Resource", IsApplication=true)]

namespace wave_android_uitest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int sm_text_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int down_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int excl_triangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green_check = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int person_outline = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int red_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int red_check = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int u23 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int u61 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int u62 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int white_button = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001e
			public const int action_activity = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int action_my_life = 2131165215;
			
			// aapt resource value: 0x7f070002
			public const int activity_image = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int activity_root = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int activity_text = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int body = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int drop_arrow = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int editText1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int forgot_password = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int imageView1 = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int listView1 = 2131165185;
			
			// aapt resource value: 0x7f07001c
			public const int login = 2131165212;
			
			// aapt resource value: 0x7f07000a
			public const int login_btn = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int login_facebook = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int login_layout = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int logo = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int pager = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int parent_view = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int rb11 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int rb12 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int rb13 = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int rg1 = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public const int root = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int sign_btn = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int sign_facebook = 2131165196;
			
			// aapt resource value: 0x7f07001d
			public const int signup = 2131165213;
			
			// aapt resource value: 0x7f070012
			public const int spinner = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int splash = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int title = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int signup = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int splash = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int tab1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int test2_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int test_layout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_actions = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int activity_action = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int my_life_action = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
